### ISSUE TITLE
Refactor Whisk class for swift4

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-swift#6]
Refactor [_Whisk.swift](https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/core/swift3Action/spm-build/_Whisk.swift) to use URLSession and Codable for JSON management.

Create copy and add into `/core/swift4Action/spm-build/_Whisk.swift`

**Comment by nacho4d** [comment]
@csantanapr 
I just saw current implementation of _Whisk.swift and it is using already URLSession.
If you are planning to have two releases (As @rolivieri said in #3 ) them current implementation should be ok for swift 4.

Is there anything I can help here to make happen open whisk with swift4 sometime soon?. I am supposed to implement something with cloud functions and it would like to use swift4 if possible. otherwise I think I will fallback to nodejs8 or java runtimes :(

**Comment by nacho4d** [comment]
Correction: current implementation is not using URLSession but has an unused function which uses URLSession. It just need to accept the http method as a parameter rather than `"POST"` hardcoded.

I still wonder what it stopping the swift4 support, If there is something I can do I am glad to help.

**Comment by csantanapr** [comment]
Hi @nacho4d I have initial swift 4 implementation ready, I'm working on adding tests cases for the _Whisk.swift

You can check out progress in #1 

This initial support to get a base swift4 image, that we can build on top of it. There is a lot that can be accomplish in user land via compiling and zipping actions which is more performant.

I will be glad to get more folks to help out like your self, thanks and keep in touch.

**Comment by csantanapr** [comment]
@nacho4d I switched to use URLSession now
https://github.com/csantanapr/incubator-openwhisk-runtime-swift/blob/swift_4/core/swift4Action/spm-build/_Whisk.swift

feel free to review and provide feedback.

**Comment by csantanapr** [comment]
We are using urlSession now
https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/core/swift4Action/spm-build/_Whisk.swift#L105

**Comment by nacho4d** [comment]
Sorry for the late response. I am excited about this!
